### ISSUE TITLE
missing from your compressed file

### ISSUE THREAD

**Issue by bsxlb6** [JinnnK/TGRF#2]
Hello

it seems that something is missing from your compressed file. Because my test results are shown below. 

Failed to get get_args function from  trained_models/TGRF_new /arguments.py
Failed to get Config function from  trained_models/TGRF_new
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    main()
  File "test.py", line 72, in main
    os.mkdir(log_file)
FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/TGRF_new/test'

If it's convenient, I hope you can provide me with the missing files. 

Wishing you all the best.

**Comment by JinnnK** [comment]
Hello,

It seems that there might be an issue with loading the data from `trained_models`. There are two potential reasons for this issue:

1. Missing Files:
   Please ensure that you have run `train.py` to train the model before running `test.py`. If `train.py` has been executed properly, check that the relevant files exist in the `trained_models` directory.

2. Incorrect Path Specification:
   In `python.py`, on line 23, ensure that you set the path for the trained model correctly:
   
   ```
   parser.add_argument('--model_dir', type=str, default='trained_models/TGRF_new')
   ```
   
   If the path is not set correctly, the program may not be able to load the saved model.

Thank you.

**Comment by bsxlb6** [comment]
Thank you for your prompt reply. I have resolved the issue
